# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: flutter_android_build_dev

on:
  push:
    branches: [ "non-existing-branch" ]
  pull_request:
    branches: [ "non-existing-branch" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout to the selected branch
      - name: Checkout
        uses: actions/checkout@v3

      # Download and install flutter packages
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
         flutter-version: "3.16.5"
         channel: 'stable'

      # Get Flutter project dependencies
      - name: Get dependencies
        run: flutter pub get

      # Build APK
      - name: Build APK
        run: flutter build apk --release
        
      # Upload Artifact Build
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk-file
          path: build/app/outputs/apk/release/*.apk
